version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8091:8000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: spoural_db
    environment:
      POSTGRES_DB: spoural
      POSTGRES_USER: spoural
      POSTGRES_PASSWORD: spoural
    ports:
      - "8092:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
