# Generated by Django 5.1.1 on 2024-10-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='data',
        ),
    ]
