# Generated by Django 5.1.1 on 2024-10-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0002_remove_sheet_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='data',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
