# Generated by Django 5.1.1 on 2024-10-20 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0003_sheet_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('defects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_app.defects')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_app.materials')),
            ],
        ),
        migrations.AddField(
            model_name='defects',
            name='recommendations',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='excel_app.recommendations', to_field='name'),
        ),
    ]
