# Generated by Django 5.1.1 on 2024-10-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0004_defects_recommendations_materials_constructiontypes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='defects',
        ),
        migrations.AddField(
            model_name='materials',
            name='defects',
            field=models.ManyToManyField(to='excel_app.defects'),
        ),
    ]
