# Generated by Django 5.1.1 on 2024-10-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0005_remove_materials_defects_materials_defects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructiontypes',
            name='material',
        ),
        migrations.AddField(
            model_name='constructiontypes',
            name='material',
            field=models.ManyToManyField(to='excel_app.materials'),
        ),
    ]
