# Generated by Django 5.1.1 on 2024-10-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0006_remove_constructiontypes_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='recommendations',
            field=models.ManyToManyField(to='excel_app.recommendations'),
        ),
    ]
