# Generated by Django 5.1.1 on 2024-10-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0007_materials_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='defects',
            field=models.ManyToManyField(blank=True, to='excel_app.defects'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='excel_app.recommendations'),
        ),
    ]
