# Generated by Django 5.1.1 on 2024-10-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0008_alter_materials_defects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='defects',
            field=models.ManyToManyField(to='excel_app.defects'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='recommendations',
            field=models.ManyToManyField(to='excel_app.recommendations'),
        ),
    ]
