# Generated by Django 5.1.1 on 2024-11-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0009_alter_materials_defects_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructiontypes',
            options={'verbose_name': 'Тип конструкции', 'verbose_name_plural': 'Типы конструкций'},
        ),
        migrations.AlterModelOptions(
            name='defects',
            options={'verbose_name': 'Дефект', 'verbose_name_plural': 'Дефекты'},
        ),
        migrations.AlterModelOptions(
            name='materials',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='recommendations',
            options={'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.AlterModelOptions(
            name='sheet',
            options={'verbose_name': 'Лист', 'verbose_name_plural': 'Листы'},
        ),
        migrations.AddField(
            model_name='sheet',
            name='countCell',
            field=models.CharField(default='AK56', max_length=10),
        ),
        migrations.AddField(
            model_name='sheet',
            name='name',
            field=models.CharField(default='aaa', max_length=255),
            preserve_default=False,
        ),
    ]
