# Generated by Django 5.1.1 on 2024-11-06 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0010_alter_constructiontypes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'MultiSelect'), ('multinumber', 'MultiNumber'), ('documentation', 'Documentation')], max_length=15)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('mask', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('placeholder', models.CharField(max_length=255)),
                ('settings', models.JSONField(blank=True, null=True)),
                ('construction_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excel_app.constructiontypes', to_field='name')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
    ]
