# Generated by Django 5.1.1 on 2024-11-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0011_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'MultiSelect'), ('multinumber', 'MultiNumber'), ('documentation', 'Documentation'), ('bool', 'Bool')], max_length=15),
        ),
    ]
