# Generated by Django 5.1.1 on 2024-11-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0012_alter_fields_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='mask',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fields',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
