# Generated by Django 5.1.1 on 2024-11-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0013_alter_fields_mask_alter_fields_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='countCell',
            field=models.CharField(blank=True, default='AK56', max_length=10, null=True),
        ),
    ]
