# Generated by Django 5.1.1 on 2024-11-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0014_alter_sheet_countcell'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fields',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
