# Generated by Django 5.1.1 on 2024-11-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0015_fields_position_fields_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
