# Generated by Django 5.1.1 on 2024-12-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0016_fields_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='subsection',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
