# Generated by Django 5.1.1 on 2024-12-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0017_sheet_section_sheet_subsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='subsection',
            new_name='subsections',
        ),
    ]
