# Generated by Django 5.1.1 on 2024-12-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0018_rename_subsection_sheet_subsections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='subsections',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
