# Generated by Django 5.1.1 on 2024-12-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0019_alter_sheet_subsections'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='contentSection',
            field=models.BooleanField(default=False),
        ),
    ]
