# Generated by Django 5.1.1 on 2024-12-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0020_sheet_contentsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'MultiSelect'), ('multinumber', 'MultiNumber'), ('table', 'Table'), ('bool', 'Bool')], max_length=15),
        ),
    ]
