# Generated by Django 5.1.1 on 2025-01-30 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0021_alter_fields_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects',
            name='recommendations',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='excel_app.recommendations', to_field='name'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='excel_app.recommendations'),
        ),
    ]
