# Generated by Django 5.1.1 on 2025-01-30 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0022_alter_defects_recommendations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects',
            name='recommendations',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='excel_app.recommendations', to_field='name'),
        ),
    ]
