# Generated by Django 5.1.1 on 2025-01-30 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0024_alter_defects_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects',
            name='recommendations',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='excel_app.recommendations', to_field='name'),
        ),
    ]
