# Generated by Django 5.1.1 on 2025-02-06 18:16

import apps.excel_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0025_alter_defects_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=apps.excel_app.models.sheet_upload_to),
        ),
    ]
