# Generated by Django 5.1.1 on 2025-02-26 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0028_alter_defects_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects',
            name='recommendations',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='excel_app.recommendations', to_field='name'),
        ),
    ]
