# Generated by Django 5.1.1 on 2025-02-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0029_alter_defects_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructiontypes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='constructiontypes',
            name='material',
            field=models.ManyToManyField(related_name='construction_types', to='excel_app.materials'),
        ),
        migrations.AlterField(
            model_name='defects',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='defects',
            name='recommendations',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='excel_app.recommendations'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='defects',
            field=models.ManyToManyField(related_name='materials', to='excel_app.defects'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materials',
            name='recommendations',
            field=models.ManyToManyField(blank=True, related_name='materials', to='excel_app.recommendations'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
