# Generated by Django 5.1.1 on 2025-02-26 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0030_alter_constructiontypes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructiontypes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='constructiontypes',
            name='material',
            field=models.ManyToManyField(to='excel_app.materials'),
        ),
        migrations.AlterField(
            model_name='defects',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='defects',
            name='recommendations',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='excel_app.recommendations', to_field='name'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='defects',
            field=models.ManyToManyField(to='excel_app.defects'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='excel_app.recommendations'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
