# Generated by Django 5.1.1 on 2025-02-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0032_alter_defects_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовое поле'), ('number', 'Числовое поле'), ('select', 'Выбор'), ('multiselect', 'Множественный выбор'), ('multinumber', 'Множественное число'), ('table', 'Таблица'), ('date', 'Дата'), ('bool', 'Да/Нет'), ('media', 'Изображение')], max_length=15),
        ),
    ]
