# Generated by Django 5.1.1 on 2025-03-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0033_alter_fields_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='is_appendix',
            field=models.BooleanField(default=False, verbose_name='Является приложением'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='contentSection',
            field=models.BooleanField(default=False, verbose_name='Включать в содержание'),
        ),
    ]
