# Generated by Django 5.1.1 on 2025-03-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0034_sheet_is_appendix_alter_sheet_contentsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='sheet',
            name='excel_name',
            field=models.CharField(default='Лист', max_length=31),
        ),
    ]
