# Generated by Django 5.1.1 on 2025-03-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0035_rename_name_sheet_full_name_sheet_excel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='excel_name',
            field=models.CharField(default='Название листа в Excel', max_length=31),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='full_name',
            field=models.CharField(default='Название листа', max_length=255),
        ),
    ]
