# Generated by Django 5.1.1 on 2024-10-14 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='isReady',
            field=models.IntegerField(choices=[(0, 'Loading'), (1, 'Success'), (2, 'Error')], default=0),
        ),
    ]
