# Generated by Django 5.1.1 on 2024-10-20 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0004_defects_recommendations_materials_constructiontypes_and_more'),
        ('user', '0002_userdata_date_created_userdata_isready'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date')], max_length=10)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('mask', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('placeholder', models.CharField(max_length=255)),
                ('construction_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excel_app.constructiontypes', to_field='name')),
            ],
        ),
    ]
