# Generated by Django 5.1.1 on 2024-10-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='mask',
            field=models.TextField(blank=True, null=True),
        ),
    ]
