# Generated by Django 5.1.1 on 2024-10-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userinput_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
