# Generated by Django 5.1.1 on 2024-11-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userinput_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='mask',
            field=models.CharField(max_length=255),
        ),
    ]
