# Generated by Django 5.1.1 on 2024-11-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userdata_options_alter_userinput_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='mask',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='placeholder',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
