# Generated by Django 5.1.1 on 2024-11-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userinput_mask_alter_userinput_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='mask',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
