# Generated by Django 5.1.1 on 2024-11-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_userinput_mask_alter_userinput_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='file_name',
            field=models.CharField(default=21, max_length=255),
            preserve_default=False,
        ),
    ]
