# Generated by Django 5.1.1 on 2024-11-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userdata_file_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInput',
        ),
    ]
