# Generated by Django 5.1.1 on 2024-12-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_userinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
