# Generated by Django 5.1.1 on 2025-01-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_userdata_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='file_name',
            new_name='filename',
        ),
    ]
