# Generated by Django 5.1.1 on 2025-01-21 13:43

import apps.user.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_date_created_userdata_datecreated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.user.models.user_images_upload_path)),
                ('key', models.CharField(max_length=255)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user.userdata')),
            ],
        ),
    ]
