# Generated by Django 5.1.1 on 2025-01-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_userdatafile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdatafile',
            options={'verbose_name': 'Изображение пользователя', 'verbose_name_plural': 'Изображения пользователей'},
        ),
    ]
