# Generated by Django 5.1.1 on 2025-02-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_userdatafile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='reportName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
