# Generated by Django 5.1.1 on 2025-02-18 16:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_userdata_reportname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='uniqueId',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
