name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH and Run Scripts on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/applications/ExcelApp
            git pull
            find scripts/ -type f -iname "*.sh" -exec chmod +x {} \;
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'frontend/'; then
              sh scripts/reload_front.sh
            fi
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'backend/'; then
              sh scripts/reload_back.sh
            fi
            sh scripts/clean_up.sh
